# Generated by Django 4.1 on 2022-08-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp_lama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='chain_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('date', 'chain_id', 'block_no')},
        ),
    ]
