# Generated by Django 4.1 on 2022-08-28 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lp_lama', '0002_block_chain_id_alter_block_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, unique=True)),
                ('token0', models.CharField(max_length=50)),
                ('token1', models.CharField(max_length=50)),
                ('chain_ids', models.TextField()),
                ('tvl', models.IntegerField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lp_lama.exchange')),
            ],
        ),
    ]
